class FormOptions {
  static identifyOptions = [
    { value: 'lesbian', text: 'Lesbian' },
    { value: 'gay', text: 'Gay' },
    { value: 'bisexual', text: 'Bisexual' },
    { value: 'trans', text: 'Trans' },
    { value: 'genderqueer', text: 'Genderqueer' },
    { value: 'queer', text: 'Queer' },
    { value: 'ally', text: 'Ally' },
    { value: 'other', text: 'Other' }
  ]

  static pronounOptions = [
    { value: 'she', text: 'She / Her' },
    { value: 'he', text: 'He / Him' },
    { value: 'they', text: 'They / Them' }
  ]

  static industryOptions = [
    { value: 'Accounting', text: 'Accounting' },
    { value: 'Airlines/Aviation', text: 'Airlines/Aviation' },
    { value: 'Alternative Dispute Resolution', text: 'Alternative Dispute Resolution' },
    { value: 'Alternative Medicine', text: 'Alternative Medicine' },
    { value: 'Animation', text: 'Animation' },
    { value: 'Architecture/Planning', text: 'Architecture/Planning' },
    { value: 'Arts/Crafts', text: 'Arts/Crafts' },
    { value: 'Automotive', text: 'Automotive' },
    { value: 'Aviation/Aerospace', text: 'Aviation/Aerospace' },
    { value: 'Banking/Mortgage', text: 'Banking/Mortgage' },
    { value: 'Biotechnology/Greentech', text: 'Biotechnology/Greentech' },
    { value: 'Broadcast Media', text: 'Broadcast Media' },
    { value: 'Building Materials', text: 'Building Materials' },
    { value: 'Business Supplies/Equipment', text: 'Business Supplies/Equipment' },
    { value: 'Capital Markets/Hedge Fund/Private Equity', text: 'Capital Markets/Hedge Fund/Private Equity' },
    { value: 'Chemicals', text: 'Chemicals' },
    { value: 'Civic/Social Organization', text: 'Civic/Social Organization' },
    { value: 'Civil Engineering', text: 'Civil Engineering' },
    { value: 'Commercial Real Estate', text: 'Commercial Real Estate' },
    { value: 'Computer Games', text: 'Computer Games' },
    { value: 'Computer Hardware', text: 'Computer Hardware' },
    { value: 'Computer Networking', text: 'Computer Networking' },
    { value: 'Computer Software Engineering', text: 'Computer Software Engineering' },
    { value: 'Computer Network Security', text: 'Computer Network Security' },
    { value: 'Construction', text: 'Construction' },
    { value: 'Consumer Electronics', text: 'Consumer Electronics' },
    { value: 'Consumer Goods', text: 'Consumer Goods' },
    { value: 'Consumer Services', text: 'Consumer Services' },
    { value: 'Cosmetics', text: 'Cosmetics' },
    { value: 'Co-working spaces / Event Spaces', text: 'Co-working spaces / Event Spaces' },
    { value: 'Dairy', text: 'Dairy' },
    { value: 'Defense/Space', text: 'Defense/Space' },
    { value: 'Design', text: 'Design' },
    { value: 'E-Learning', text: 'E-Learning' },
    { value: 'Education', text: 'Education' },
    { value: 'Electrical/Electronic Manufacturing', text: 'Electrical/Electronic Manufacturing' },
    { value: 'Entertainment/Movie Production', text: 'Entertainment/Movie Production' },
    { value: 'Environmental Services', text: 'Environmental Services' },
    { value: 'Events Services', text: 'Events Services' },
    { value: 'Executive Office', text: 'Executive Office' },
    { value: 'Facilities Services', text: 'Facilities Services' },
    { value: 'Farming', text: 'Farming' },
    { value: 'Fashion/Apparel', text: 'Fashion/Apparel' },
    { value: 'Financial Services', text: 'Financial Services' },
    { value: 'Fine Art', text: 'Fine Art' },
    { value: 'Fishery', text: 'Fishery' },
    { value: 'Food Production', text: 'Food Production' },
    { value: 'Food/Beverages', text: 'Food/Beverages' },
    { value: 'Fundraising', text: 'Fundraising' },
    { value: 'Furniture', text: 'Furniture' },
    { value: 'Gambling/Casinos', text: 'Gambling/Casinos' },
    { value: 'Glass/Ceramics/Concrete', text: 'Glass/Ceramics/Concrete' },
    { value: 'Government Administration', text: 'Government Administration' },
    { value: 'Government Relations', text: 'Government Relations' },
    { value: 'Graphic Design/Web Design', text: 'Graphic Design/Web Design' },
    { value: 'Health/Fitness', text: 'Health/Fitness' },
    { value: 'Higher Education/Acadamia', text: 'Higher Education/Acadamia' },
    { value: 'Hospital/Health Care', text: 'Hospital/Health Care' },
    { value: 'Hospitality', text: 'Hospitality' },
    { value: 'Human Resources/HR', text: 'Human Resources/HR' },
    { value: 'Import/Export', text: 'Import/Export' },
    { value: 'Individual/Family Services', text: 'Individual/Family Services' },
    { value: 'Industrial Automation', text: 'Industrial Automation' },
    { value: 'Information Services', text: 'Information Services' },
    { value: 'Information Technology/IT', text: 'Information Technology/IT' },
    { value: 'Insurance', text: 'Insurance' },
    { value: 'International Affairs', text: 'International Affairs' },
    { value: 'International Trade/Development', text: 'International Trade/Development' },
    { value: 'Internet', text: 'Internet' },
    { value: 'Investment Banking/Venture', text: 'Investment Banking/Venture' },
    { value: 'Investment Management/Hedge Fund/Private Equity', text: 'Investment Management/Hedge Fund/Private Equity' },
    { value: 'Judiciary', text: 'Judiciary' },
    { value: 'Law Enforcement', text: 'Law Enforcement' },
    { value: 'Law Practice/Law Firms', text: 'Law Practice/Law Firms' },
    { value: 'Legal Services', text: 'Legal Services' },
    { value: 'Legislative Office', text: 'Legislative Office' },
    { value: 'Leisure/Travel', text: 'Leisure/Travel' },
    { value: 'Library', text: 'Library' },
    { value: 'Logistics/Procurement', text: 'Logistics/Procurement' },
    { value: 'Luxury Goods/Jewelry', text: 'Luxury Goods/Jewelry' },
    { value: 'Machinery', text: 'Machinery' },
    { value: 'Management Consulting', text: 'Management Consulting' },
    { value: 'Maritime', text: 'Maritime' },
    { value: 'Market Research', text: 'Market Research' },
    { value: 'Marketing/Advertising/Sales', text: 'Marketing/Advertising/Sales' },
    { value: 'Mechanical or Industrial Engineering', text: 'Mechanical or Industrial Engineering' },
    { value: 'Media Production', text: 'Media Production' },
    { value: 'Medical Equipment', text: 'Medical Equipment' },
    { value: 'Medical Practice', text: 'Medical Practice' },
    { value: 'Mental Health Care', text: 'Mental Health Care' },
    { value: 'Military Industry', text: 'Military Industry' },
    { value: 'Mining/Metals', text: 'Mining/Metals' },
    { value: 'Motion Pictures/Film', text: 'Motion Pictures/Film' },
    { value: 'Museums/Institutions', text: 'Museums/Institutions' },
    { value: 'Music', text: 'Music' },
    { value: 'Nanotechnology', text: 'Nanotechnology' },
    { value: 'Newspapers/Journalism', text: 'Newspapers/Journalism' },
    { value: 'Non-Profit/Volunteering', text: 'Non-Profit/Volunteering' },
    { value: 'Oil/Energy/Solar/Greentech', text: 'Oil/Energy/Solar/Greentech' },
    { value: 'Online Publishing', text: 'Online Publishing' },
    { value: 'Other Industry', text: 'Other Industry' },
    { value: 'Outsourcing/Offshoring', text: 'Outsourcing/Offshoring' },
    { value: 'Package/Freight Delivery', text: 'Package/Freight Delivery' },
    { value: 'Packaging/Containers', text: 'Packaging/Containers' },
    { value: 'Paper/Forest Products', text: 'Paper/Forest Products' },
    { value: 'Performing Arts', text: 'Performing Arts' },
    { value: 'Pharmaceuticals', text: 'Pharmaceuticals' },
    { value: 'Philanthropy', text: 'Philanthropy' },
    { value: 'Photography', text: 'Photography' },
    { value: 'Plastics', text: 'Plastics' },
    { value: 'Political Organization', text: 'Political Organization' },
    { value: 'Primary/Secondary Education', text: 'Primary/Secondary Education' },
    { value: 'Printing', text: 'Printing' },
    { value: 'Professional Training', text: 'Professional Training' },
    { value: 'Program Development', text: 'Program Development' },
    { value: 'Public Relations/PR', text: 'Public Relations/PR' },
    { value: 'Public Safety', text: 'Public Safety' },
    { value: 'Publishing Industry', text: 'Publishing Industry' },
    { value: 'Railroad Manufacture', text: 'Railroad Manufacture' },
    { value: 'Ranching', text: 'Ranching' },
    { value: 'Real Estate/Mortgage', text: 'Real Estate/Mortgage' },
    { value: 'Recreational Facilities/Services', text: 'Recreational Facilities/Services' },
    { value: 'Religious Institutions', text: 'Religious Institutions' },
    { value: 'Renewables/Environment', text: 'Renewables/Environment' },
    { value: 'Research Industry', text: 'Research Industry' },
    { value: 'Restaurants', text: 'Restaurants' },
    { value: 'Retail Industry', text: 'Retail Industry' },
    { value: 'Security/Investigations', text: 'Security/Investigations' },
    { value: 'Semiconductors', text: 'Semiconductors' },
    { value: 'Shipbuilding', text: 'Shipbuilding' },
    { value: 'Sporting Goods', text: 'Sporting Goods' },
    { value: 'Sports', text: 'Sports' },
    { value: 'Social Enterprise', text: 'Social Enterprise' },
    { value: 'Staffing/Recruiting', text: 'Staffing/Recruiting' },
    { value: 'Supermarkets', text: 'Supermarkets' },
    { value: 'Telecommunications', text: 'Telecommunications' },
    { value: 'Textiles', text: 'Textiles' },
    { value: 'Think Tanks', text: 'Think Tanks' },
    { value: 'Tobacco', text: 'Tobacco' },
    { value: 'Translation/Localization', text: 'Translation/Localization' },
    { value: 'Transportation', text: 'Transportation' },
    { value: 'Travel/Tourism', text: 'Travel/Tourism' },
    { value: 'Utilities', text: 'Utilities' },
    { value: 'Venture Capital/VC', text: 'Venture Capital/VC' },
    { value: 'Veterinary', text: 'Veterinary' },
    { value: 'Warehousing', text: 'Warehousing' },
    { value: 'Wholesale', text: 'Wholesale' },
    { value: 'Wine/Spirits', text: 'Wine/Spirits' },
    { value: 'Wireless', text: 'Wireless' },
    { value: 'Writing/Editing', text: 'Writing/Editing' }
  ]

  static sizeOptions = [
    { value: '0-5', text: '0-5' },
    { value: '6-10', text: '6-10' },
    { value: '11-20', text: '11-20' },
    { value: '21-50', text: '21-50' },
    { value: '51-100', text: '51-100' },
    { value: '101-200', text: '101-200' },
    { value: '201-500', text: '201-500' },
    { value: '500+', text: '500+' }
  ]

  static visibilityOptions = [
    { value: 'LGB colleagues', text: 'LGB colleagues' },
    { value: 'Trans, genderqueer colleagues', text: 'Trans / Genderqueer colleagues' },
    { value: 'Allies', text: 'Strong and vocal allies' },
    { value: 'Others', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]

  static benefitsOptions = [
    { value: 'Same-sex benefits', text: 'Same-sex benefits' },
    { value: 'Rainbow families', text: 'Rainbow family support' },
    { value: 'Trans benefits', text: 'Trans benefits / transition support' },
    { value: 'Informal Benefits', text: 'Nothing official, but LGBTQ benefits provided for individual cases.' },
    { value: 'Other', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]

  static policiesOptions = [
    { value: 'Generic non-discrimination', text: 'Generic non-discrimination' },
    { value: 'Same-sex policies', text: 'Same-sex policies' },
    { value: 'Trans policies', text: 'Trans policies' },
    { value: 'Informal policies', text: 'No policies, but leadership actively helps for individual cases.' },
    { value: 'Unenforced policies', text: 'Has same-sex/trans policies, but they are not enforced.' },
    { value: 'Others', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]

  static spaceOptions = [
    { value: 'Trans washrooms', text: 'Trans washrooms' },
    { value: 'Gender neutral washrooms', text: 'Gender neutral washrooms' },
    { value: 'Others', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]

  static communityOptions = [
    { value: 'Allies', text: 'There are allies to turn to for help or raise issues with.' },
    { value: 'Inclusive culture', text: 'Generally an inclusive company.' },
    { value: 'Comfortable calling out', text: 'I feel comfortable calling out discrimination.' },
    { value: 'LGBTQ network', text: 'Internal LGBTQ Network' },
    { value: 'D&I events', text: 'Internal Diversity & Inclusion Events' },
    { value: 'Others', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]

  static sponsorshipOptions = [
    { value: 'Public events', text: 'Hosts public events / LGBTQ initiatives' },
    { value: 'Event sponsorships', text: 'Sponsors LGBTQ events' },
    { value: 'NGO sponsorships', text: 'Sponsors LGBTQ NGOs' },
    { value: 'Advocacy', text: 'Company does public advocacy' },
    { value: 'Others', text: 'Other (please fill in at the bottom of this questionaire)' }
  ]
}

export default FormOptions
